### ISSUE TITLE
Deploy package to PyPI

### ISSUE THREAD

**Issue by bbelderbos** [BenGriffith/blackjack#17]
Same as https://github.com/BenGriffith/book-api-cli/issues/7

**Comment by bbelderbos** [comment]
@BenGriffith is it on PyPI? If so let me pip install it ... and share a win on PDM Slack! ;)

**Comment by bbelderbos** [comment]
Duh I could just have checked, nice:

- job ran fine: https://github.com/BenGriffith/blackjack/actions/runs/4140840285/jobs/7159874836
- package is up: https://pypi.org/project/play-blackjack/0.1.0/ 🎉

**Comment by BenGriffith** [comment]
Shared my win on PDM slack not too long ago :)

**Comment by bbelderbos** [comment]
Awesome, thanks!
